# struct syntax
nodes:
  node1:
    id: 5
    name: base_link1_joint
    eds_pkg: maxon_epos4_ros_canopen # optionals package  name for relative path
    eds_file: "config/CAN_M5.dcf" # path to EDS/DCF file
  node2:
    id: 6
    name: link1_link2_joint
    eds_pkg: maxon_epos4_ros_canopen # optionals package  name for relative path
    eds_file: "config/CAN_M6.dcf" # path to EDS/DCF file

defaults: # optional, all defaults can be overwritten per node
#  eds_pkg: my_config_package # optional package  name for relative path
#  eds_file: "my_config.dcf" # path to EDS/DCF file
  dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
    "60C2sub1": "10" # Interpolation time period value, to be set as the sync/interval_ms value present in canopen_bus_layer.yaml file, 10ms is recommended 
#    "607Dsub1": "-2147483648"     # disable software min limit
#    "607Dsub2": "2147483647"     # disable software max limit

#    "6084": "10000" # Profile deceleration    
#    "6085": "10000" # Quick-stop deceleration
#    "6098": "0" # No homing operation required
#    "1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127
#    "1017": "100" # heartbeat producer

# canopen_chain_node settings ..
  motor_allocator: canopen::Motor402::Allocator # select allocator for motor layer
#   motor_layer: settings passed to motor layer (plugin-specific)
  switching_state: 2 # (Operation_Enable), state for mode switching. Drive mode of operation from canopen_402 wiki

#  pos_to_device: "pos" # inc
#  pos_from_device: "obj6064" # inc 
  pos_to_device: "rint(rad2deg(pos)*4*1024*100/360)" # rad -> inc, for a MILE 800 CPT encoder and a 26:1 gearbox, 3200 = 4*800 --> 4 * 100 
  pos_from_device: "deg2rad(obj6064*360/1024*4/100)" # actual position [inc] -> rad
#  pos_to_device: "rint(rad2deg(pos)*4*1024*100/360)" # rad -> inc, for a MILE 800 CPT encoder and a 26:1 gearbox, 3200 = 4*800 --> 4 * 100 
#  pos_from_device: "deg2rad(obj6064*360/1024*4/100)" # actual position [inc] -> rad

# pos_to_device: "rint(rad2deg(pos)*4*1024*100/360)" # rad -> inc, for a MILE 800 CPT encoder and a 26:1 gearbox, 3200 = 4*800 --> 4 * 100 
#  pos_from_device: "deg2rad(obj6064*360/1024*4/100)" # actual position [inc] -> rad
  vel_to_device: "vel" # rad/s -> mdeg/s
  vel_from_device: "obj606C" # actual velocity [mdeg/s] -> rad/s
  eff_to_device: "rint(eff)" # just round to integer
  eff_from_device: "0" # unset
 
